export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <header>it is a header</header>
        {children}  
      <footer>it is a footer</footer>
      </body>
    </html>
  )
}
