import Link from "next/link";

// this is a static way to define the meta data
export const metadata = {
  title: 'product page',
  description: 'Generated by Next.js',
}

export default function product() {
  return (
    <>
    {/* we can use replace to replace the history url with the  new one */}
      <h1>Details of the product </h1>
      <Link href="/product/1">product 1</Link>
      <Link href="/product/2" replace>product 2</Link>
    </>
  );
}
